import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import myData from '../ranking_persons.json';
import styles2 from "./Test.module.css";



export default function Home() {


  function addRow(tableID) {

    console.log('myData["1"].name');

    var table = document.getElementById(tableID);
    var rowCount = table.rows.length;
    // delete all rows except the header
    for (var i = 1; i < rowCount; i++) {
      table.deleteRow(1);
    }


    for (var i = 1; i < Object.keys(myData).length + 1; i++) {
      var row = table.insertRow(i);
      var cell1 = row.insertCell(0);
      cell1.innerHTML = i;
      var cell2 = row.insertCell(1);
      cell2.innerHTML = myData[i].id;
      var cell2 = row.insertCell(2);
      cell2.innerHTML = myData[i].name;
      var cell2 = row.insertCell(3);
      cell2.innerHTML = myData[i].messages;
      var cell2 = row.insertCell(4);
      cell2.innerHTML = myData[i].connotation_scores;
      var cell2 = row.insertCell(5);
      cell2.innerHTML = myData[i].reactions;
      var cell2 = row.insertCell(6);
      cell2.innerHTML = myData[i].community_score;

    }
  }


  return (
    <div
      style={{
        backgroundColor: "#0F0F12",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script language="javascript"> addRow(dataTable) </script>
      </Head>

      <div
        style={{
          display: "flex",
          justifyContent: "center",
          flexDirection: "column",
          marginLeft: "120px",
          marginRight: "120px",
        }}
      >
        <h1
          style={{
            fontSize: "75px",
            fontFamily: "SK Cuber",
            color: "white",
            textAlign: "center",
          }}
        >
          🏀 Krause House Community Dashboard 🏀
        </h1>
      </div>

      <main className={styles.main}>
        <div
          style={{
            height: "85px",
            fontSize: "25px",
            color: "white",
            width: "80%",
          }}
        >
          <button
            className={styles2.btn2}
            style={{
              height: "70px",
              width: "150px",
              fontSize: "30px",
              marginRight: "30px",
              fontFamily: "SK Cuber",
            }}
            onClick={() => addRow("dataTable")}
          >
            Refresh
          </button>
        </div>
        <div
          style={{
            //height: "1150px",
            fontSize: "25px",
            color: "white",
            width: "80%",
          }}>
          <table id="dataTable" width="100%" border="3">
            <tr>
              <th className={styles2.th} width="200px">Ranking</th>
              <th className={styles2.th}>User ID</th>
              <th className={styles2.th}>User Name</th>
              <th className={styles2.th}>Activity Score</th>
              <th className={styles2.th}>Connotation Score</th>
              <th className={styles2.th}>Reaction Score</th>
              <th className={styles2.th}>Final Community Score</th>
            </tr>
          </table>
        </div>
      </main>

    </div>
  )
}

